### ISSUE TITLE
Extension send requests to wrong urls

### ISSUE THREAD

**Issue by shaggyone** [mshauneu/chrome-swagger-ui#9]
After the last update the extension stopped to work

Now it sends to chrome-extension scheme instead of http/https

Following curl example is shown in query log:
```
curl -X POST --header 'Content-Type: application/json' \
                       --header 'Accept: application/json' \
                       --header 'X-AUTH-TOKEN: <my token>' \
                       -d '<my data>' \
                       'chrome-extension://<my-url>'
                             ^ mistake, should not change original url scheme
                            
```

**Comment by ashertarno** [comment]
still works through Expand Operations. can be used as a work around meanwhile...

**Comment by mkrufky** [comment]
this is a duplicate of https://github.com/mshauneu/chrome-swagger-ui/issues/10 (not sure why it's closed) ... There is a patch to fix to `swagger-js` here: https://github.com/swagger-api/swagger-js/pull/913

**Comment by emreerguden** [comment]
i closed because the problem is not about swagger-chrome-extension. I tried to fix and send pull request to swager-js but i am not sure they will merge it and i am not sure if chrome-swagger-ui will get the latest version :)
I reopened #10 

They have merged the fixed, new swagger 2.2.8 will be fixed if chromw extension ui will have the latest version, this issue and 10. issue will be closed

**Comment by emreerguden** [comment]
Can you check with the version 0.0.7, if the problem is same as issue #10, then it should be resolved.

**Comment by theigl** [comment]
I'm still seeing the same issue after upgrading to 0.0.7. Is there anything else I have to do to get this working again?

**Comment by emreerguden** [comment]
if swager doc has no scheme property which should have at least "http" information new swagger ui send exceptions. Could you please check scheme information in swagger doc? If it is not exists, then it should be added to document json. Otherwise please give information about your case, let us open issue to swaggerui git hub. (For ex. my swagger doc has "schemes":["http","https"], only http is best for ex)

**Comment by theigl** [comment]
@emreerguden: Thank you very much, that was it!

**Comment by emreerguden** [comment]
Then, we shall close the issue, your welcome

**Comment by eortner** [comment]
I have the latest java lib, the latest chrome extension, and this is still an issue. There is a workaround, just not using the extension, but it is not the idea.
